### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by SebastianMucke** [wilr/silverstripe-googlesitemaps#108]
10 days ago you just updated composer installation instructions to:
`composer require "wilr/googlesitemaps"`

This is still not working for me. Shouldn't it be rather?
`composer require wilr/silverstripe-googlesitemaps`

**Comment by dhensby** [comment]
yes it should by the looks of things

**Comment by dhensby** [comment]
the composer.json probably also needs a `replaces` declared
