### ISSUE TITLE
limit should work with canIncludeInGoogleSitemap

### ISSUE THREAD

**Issue by sunnysideup** [wilr/silverstripe-googlesitemaps#112]
see:
https://github.com/wilr/silverstripe-googlesitemaps/blob/master/code/GoogleSitemap.php#L272-L284

First the code limits the numbers and then it checks for canIncludeInGoogleSitemap.  It seems to me that it should be the other way around so that you end up with empty lists (i.e. filter before limit).

**Comment by wilr** [comment]
You have to limit it prior to the loop to avoid crashing the server looping over every record. See this issue for notes on empty pages #61
