### ISSUE TITLE
Couldn\'t parse /googlesitemaps/code/GoogleSitemap.php when building config static manifest

### ISSUE THREAD

**Issue by adrian-stein** [wilr/silverstripe-googlesitemaps#114]
Hey there,

I get this error when I composer update.

`Fatal error: Couldn\'t parse C:\DIRPATH/googlesitemaps/code/GoogleSitemap.php when building config static manifest in C:\DIRPATH\framework\core\manifest\ConfigStaticManifest.php on line 247`

I am using SS 3.4.0 and dev-master of "silverstripe/googlesitemaps"

It has only stated to happen the last couple of days as I have composer updated last week.

Any ideas?

**Comment by wilr** [comment]
Hi,

Looks like dev-master now *only* supports 4.0 and the changes despite my testing don't work on 3.4. I've created a 1.6.0 release and a 1.6 branch for 3.* support.

Cheers

**Comment by adrian-stein** [comment]
Cheers. I get this now.

```
Problem 1
- The requested package silverstripe/googlesitemaps 1.6.0 exists as
silverstripe/googlesitemaps[0.2.x-dev, 1.0.x-dev, 1.1.x-dev, 1.2.0, 1.2.1,
1.2.2, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.x-dev, dev-master] but these are rejected
by your constraint.
```

Is this me or you?

**Comment by wilr** [comment]
Sorry the package name has been transfered off SilverStripe since they no longer wanted to manage it. Package name should be wilr/silverstripe-googlesitemaps I can't replace it on packagist as I have no access to the original repo

**Comment by dhensby** [comment]
@wilr - you probably want to add the "replaces" property in composer.json

**Comment by wilr** [comment]
@dhensby not sure I fully understand the documentation on that one.

I'd imagine I would write something like
```
"replace": {
    "silverstripe/googlesitemaps":"*"
}
```

But surely if you're installing silverstripe/googlesitemaps already in your composer some form of change needs to happen on that side to tell it about the `wilr` version as well?
