### ISSUE TITLE
not working with SS4 alpha7

### ISSUE THREAD

**Issue by guyvanbael** [wilr/silverstripe-googlesitemaps#120]
added to SS4 alpha7 using composer
created googlesitemaps.yml in mysite/_config (see screenshot)
dev/build/?flush leaves me with white screen (see screenshot)
![sitemaps1](https://cloud.githubusercontent.com/assets/3098809/25697143/11ad03c4-30ba-11e7-8502-38cb402fa337.png)
<img width="2032" alt="sitemaps2" src="https://cloud.githubusercontent.com/assets/3098809/25697142/11ac474a-30ba-11e7-9ea1-c2ef06338b21.png">

**Comment by wilr** [comment]
@guyvanbael Check your PHP error logs for a start, make sure you're running dev-master#526a0eec4d36899a3d3e4bf38b729595029dfc5a for 4.0 support

**Comment by guyvanbael** [comment]
@wilr Seems like i'm using that version:
          "name": "silverstripe/googlesitemaps",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/wilr/silverstripe-googlesitemaps.git",
                "reference": "526a0eec4d36899a3d3e4bf38b729595029dfc5a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/wilr/silverstripe-googlesitemaps/zipball/526a0eec4d36899a3d3e4bf38b729595029dfc5a",
                "reference": "526a0eec4d36899a3d3e4bf38b729595029dfc5a",
                "shasum": ""

**Comment by guyvanbael** [comment]
![schermafbeelding 2017-05-05 om 13 27 42](https://cloud.githubusercontent.com/assets/3098809/25743830/b235f6ac-3196-11e7-963b-caa744ed1b68.png)

**Comment by guyvanbael** [comment]
still having issues Wil. 
![schermafbeelding 2017-05-08 om 08 37 16](https://cloud.githubusercontent.com/assets/3098809/25792877/a33abf0e-33c9-11e7-92cf-2e3c97251a4a.png)

**Comment by wilr** [comment]
Try `1.7.0` release now.

**Comment by guyvanbael** [comment]
Hi @wilr 
using 1.7.0 throws an error that it's using the wrong namespace(screenshot1), so i changed this in GoogleSitemap.php:
//use SilverStripe\ORM\Versioning\Versioned;
use SilverStripe\Versioned\Versioned; 
That seemed to solve the problem, but then i got the wrong link (screenshot2). 
Clicking the link throws me another error (screenshot3)

Thanks for all the help!

**Comment by wilr** [comment]
Sorry! Have done you a disservice by quickly fixing it without actually having a 4.0-a7 build on my machine - never a foolproof way. I've downloaded a7 and setup googlesitemaps. Try 1.7.1

**Comment by guyvanbael** [comment]
@wilr No problem Wil. It works flawless now! Using this as a standard in all my projects (about a 100 at this moment...). Thanks for keeping up the good work.

Cheers,
Guy

**Comment by guyvanbael** [comment]
@wilr  Hey Will this seems to broken again In SS4beta1. Adding the cusom yml file results in blank screen...

**Comment by wilr** [comment]
@guyvanbael I've just tested it against SilverStripe 4.0.x-dev and 4.0-beta1 and works fine out of the box. Have you got a specific error message like last time?

**Comment by guyvanbael** [comment]
@wilr Did som more testing. Removed it and installed dev-master using composer. Doing that doesn't cause issues (module works, even with the custom yml). Then i dit a dev/buil/?flush and all is broke (internal server error 500). The only thing that helps is to remove it an reinstall.
![schermafbeelding 2017-07-10 om 08 34 10](https://user-images.githubusercontent.com/3098809/28005462-fdd3d72c-654a-11e7-8359-078002d136a9.png)

**Comment by guyvanbael** [comment]
@wilr adding googlesitemaps.yml in my config dir results in the white screen....

**Comment by wilr** [comment]
@guyvanbael As per last time - server log for more information. Are you running latest dev-master?

**Comment by guyvanbael** [comment]
@wilr found the solution. I copy-pasted the yml content from the docs whic resulted in having tabs as indentation as opposed to spaces. I edited the yml file and whoppa....!

;-) feeling a bit stupid now, but problem solved. Thnx for pointing me to the error logs Will!
