### ISSUE TITLE
Possible to include redirected pages?

### ISSUE THREAD

**Issue by JustinTBrown** [wilr/silverstripe-googlesitemaps#123]
I'd like to include a Redirector page in the sitemap. Looking at GoogleSitemap.php it looks like there is an option for `exclude_redirector_pages` which defaults to true. I've tried setting it to false in googlesitemaps.yml and then flushing sitemap.xml, but the redirected page isn't being picked up.

I should also mention that the Redirector page is set to not show up in menus, but DO show up in search. My config includes `use_show_in_search: true`.

Any ideas?

**Comment by dhensby** [comment]
in 3.x false values in config can be ignored, please see https://github.com/silverstripe/silverstripe-framework/issues/5016

You'll have to set the config value in PHP, I'm afraid :(

**Comment by dhensby** [comment]
@wilr would you mind making me an admin of the repo? I'm happy to help maintain and close issues, etc - at the moment I can't do anything :(
