### ISSUE TITLE
Include actions (custom pages) that aren't DataObjects

### ISSUE THREAD

**Issue by patricknelson** [wilr/silverstripe-googlesitemaps#125]
I was reviewing my webmaster tools Search Console and realized some pages were indexed but were not actually submitted via my sitemap. At that point I realized that most of those pages were special pages based on custom controller actions. This may relate to https://github.com/wilr/silverstripe-googlesitemaps/issues/59 (closed).

Basically the idea is that if you have custom actions (and including those which may be ID's on those actions), it'd be great to have some method of incorporating that into your sitemap. How can we implement this? There are two main hurdles:

- Itemizing actions with no ID
- Itemizing custom URL's under actions which do contain/require ID's

Possible implementations & hurdles:

- Discovering (or deliberately exposing) actions without ID's may be relatively simple. Require a controller to expose those actions as indexable individually, using a static method (e.g. `->getSitemapActions()`). i.e. Not exposed by default, with default value being `[]` if not overridden.
  - ~How to pull titles from this? Possibly use internal routing techniques, e.g. `Director::test(...)` sort of like how `FunctionalTest` loads pages?~
- Ability to define/configure how action ID's are determined (which **can** be strings **or** numeric). -
  - This could get tricky, since an action could have a vast number of possible ID's under it, so a DataList would best to be returned here. Then, how do you define the column to utilize when determining what the ID should be here?

**Comment by dhensby** [comment]
Could it not work a similar way to static publisher module where a page can define a set of child-routes that exist on the page type/controller?

It feels a bit over engineered to think up an API which allows the SiteMap to work out all the routes when we could just supply a list of all the URLs to include instead.

**Comment by patricknelson** [comment]
That's fine. Also: Could you provide link to documentation on that you're referring to?

Basically: For this to work properly, there needs to be a way to at least return an array/iterable that contains URL's + title's so that they may be arbitrary.

A potentially important point above to consider on implementation of this (for flexibility, albeit possibly over-engineered as well) is the use of `foreach` to iterate over the list which is provided as an `array` or `Traversable`. This is so that generators could possibly be used help ensure we don't kill memory or page load times for extremely long lists of pages (PHP >5.5).

**Comment by dhensby** [comment]
see: https://github.com/silverstripe/silverstripe-staticpublisher/blob/master/docs/en/StaticPublisher.md#usage

in particular `allPagesToCache` and `subPagesToCache`

**Comment by patricknelson** [comment]
Next question is:  How to expose the array of URL's? Personally I'm thinking just having a method on an object which `GoogleSitemap` then calls. It knows to call it based on YAML config (i.e. setting `static_url_providers`) or static method call similar to `::register_dataobject(...)`. This is to reduce the overhead of constantly loading/passing potentially large arrays for configuration on 99.99% of page loads when it's not necessary (hence the inversion).

Also, we'd need to think of how to properly take care of priority, since that will vary (and may not always be directly associated with depth).

**Comment by wilr** [comment]
At the moment you can use `GoogleSitemap::register_route()` manually to register individual urls. You could manually invoke this on each objects `canIncludeInGoogleSitemap()` call and provide the URL actions etc. If any modifications to those API's need to be made reopen this. An API might be required for dealing with large record sets..

**Comment by patricknelson** [comment]
Thanks @wilr! Actual documentation for this apparently exists here (took a few months to get here, but for any future time travelers stumbling here from Google with the same issue): https://github.com/wilr/silverstripe-googlesitemaps/blob/master/docs/en/index.md#including-custom-routes
