### ISSUE TITLE
SS4: Last Change date isn't formatted

### ISSUE THREAD

**Issue by axllent** [wilr/silverstripe-googlesitemaps#127]
The *Last Change* field in the sitemap displays a number rather than a date with `$LastEdited.Format(c)`. This may be a SilverStripe bug, but I thought I'd report it here for starters to get your feedback first.

I've tested with SS4 beta-3 and dev, both have the same issue (I'm not sure about older beta versions). Also tested with PHP 5.6.31 & 7.1.10. Simply doing `echo date('c');` in PHP does produce an ISO 8601 date.

![screen shot 2017-10-11 at 11 18 42-fullpage](https://user-images.githubusercontent.com/1463435/31413562-59392eea-ae76-11e7-8a53-1a36168d2329.png)

**Comment by wilr** [comment]
This is because the date format in `DBDate` is now no longer PHP date formats but  http://userguide.icu-project.org/formatparse/datetime.

**Comment by guyvanbael** [comment]
@wilr can this be fixed? Google treats it as an error...
<img width="1175" alt="schermafbeelding 2017-12-10 om 13 52 23" src="https://user-images.githubusercontent.com/3098809/33805017-8a95baa2-ddb1-11e7-961d-aef2927b581d.png">

**Comment by guyvanbael** [comment]
changed the template to format $lastedited, but still facing the errors and my pages aren't indexed.
<img width="967" alt="schermafbeelding 2017-12-12 om 09 16 54" src="https://user-images.githubusercontent.com/3098809/33874149-08379dd2-df1e-11e7-80ef-f0364bc49bad.png">
<img width="345" alt="schermafbeelding 2017-12-12 om 09 17 05" src="https://user-images.githubusercontent.com/3098809/33874150-0851676c-df1e-11e7-80f1-878f9d3681fa.png">

**Comment by guyvanbael** [comment]
changing $LastEdited.Format('Y-m-d') to $LastEdited.Format('y-MM-dd') does the trick!

**Comment by wilr** [comment]
@guyvanbael did you want to submit a PR? I thought this had been fixed: https://github.com/wilr/silverstripe-googlesitemaps/blob/master/templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss#L7

**Comment by guyvanbael** [comment]
@wilr  i was going to make a PR, but the i saw that the source file i edited was different. So i went back to check which version composer installed on my project. It was 1.8
It seems that this branch doesn't exist anymore.... If i still have to make this pr, i'd be happy to.
Is $LastEdited.Format(YYYY-MM-dd) the same as $LastEdited.Format('y-MM-dd')? Then i guess master branch is ok. But i think it's weird that composer installed this 1.8 branch
"name": "wilr/silverstripe-googlesitemaps",
            "version": "1.8.0",
            "source": {
                "type": "git",
                "url": "https://github.com/wilr/silverstripe-googlesitemaps.git",
                "reference": "b40a66422babc0e65d661f12b21913f2626d0343"
            },

**Comment by wilr** [comment]
Fixed in `2.0.0`
