### ISSUE TITLE
SS4 - style.css File not found

### ISSUE THREAD

**Issue by mr-macedawg** [wilr/silverstripe-googlesitemaps#129]
resources/wilr/silverstripe-googlesitemaps/css/style.css

Returns 404 error.

**Comment by wilr** [comment]
Have you installed via composer?

**Comment by mr-macedawg** [comment]
I sure have.

**Comment by wilr** [comment]
Do you see any files in your resources folder then? This module should expose that directory.

**Comment by mr-macedawg** [comment]
I don't see a wilr folder inside the resources fold.
<img width="532" alt="screen shot 2017-11-30 at 8 55 02 pm" src="https://user-images.githubusercontent.com/23121194/33427374-cc55efdc-d610-11e7-8156-4ca9b0299db3.png">

**Comment by mr-macedawg** [comment]
I should add that this was installed using composer require silverstripe/googlesitemaps. Changing to composer require "wilr/silverstripe-googlesitemaps" made it work correctly.

**Comment by wilr** [comment]
Sweet yep module isn't supported by silverstripe any more.

**Comment by guyvanbael** [comment]
seems like it's broken again in 4.0.1 I installed "wilr/silverstripe-googlesitemaps" using composer
<img width="1482" alt="schermafbeelding 2018-01-29 om 08 34 55" src="https://user-images.githubusercontent.com/3098809/35498636-694503e0-04cf-11e8-9a10-d386c898e415.png">
