### ISSUE TITLE
Exclude redirected URLs

### ISSUE THREAD

**Issue by yellowmamba** [wilr/silverstripe-googlesitemaps#134]
Hi there,

I understand that by default you exclude redirected URLs that are of type RedirectorPage, but we also have redirections manually done in the code like following:

```
if($this->Children()->
    $this->redirect($this->Children()->First()->AbsoluteLink());
}
```

This, understandably won't be picked up automatically. What's the best way to exclude URLs like this?

**Comment by wilr** [comment]
Hi @yellowmamba you can set the Priority to `-1` for the page and it won't be included or you can override the `alterCanIncludeInGoogleSitemap()` on the `Page` class.
