### ISSUE TITLE
fluent support alternate language

### ISSUE THREAD

**Issue by guyvanbael** [wilr/silverstripe-googlesitemaps#135]
Using SS4.0.1 with fluent and googlesitemaps. When looking at the pagesource of the sitemap.xml, there is no reference to the alternate languages.
In ss3 something like this showed up

```
<xhtml:link
--
  | rel="alternate"
  | hreflang="nl-NL"
  | href="https://www.mydomain.com/"
  | />
  |  
  | <xhtml:link
  | rel="alternate"
  | hreflang="en-US"
  | href="https://www.mydomain.com/en/"
  | />

```
In SS4.0.1 only the pages from the default locale are in the source.

**Comment by guyvanbael** [comment]
it seems that this is a fluent-related issue.
Since it's adressed by https://github.com/tractorcow/silverstripe-fluent/issues/332
i'm closing this.

**Comment by wernerkrauss** [comment]
As the URL of the related issue changed, here the updated link: https://github.com/tractorcow-farm/silverstripe-fluent/issues/332
