### ISSUE TITLE
xsl issue with version 2.0.1 on SS4.1

### ISSUE THREAD

**Issue by guyvanbael** [wilr/silverstripe-googlesitemaps#145]
Nothing is loading...
<img width="429" alt="schermafbeelding 2018-03-20 om 14 42 40" src="https://user-images.githubusercontent.com/3098809/37658603-3a351a44-2c4e-11e8-94f0-d30f90a3b16b.png">

**Comment by wilr** [comment]
Tried `2.1.1`? Make sure you flush.

**Comment by guyvanbael** [comment]
tried 2.1.1, flushed.... same issue
<img width="1539" alt="schermafbeelding 2018-03-21 om 08 01 08" src="https://user-images.githubusercontent.com/3098809/37697627-1f42fb8a-2cde-11e8-9fdf-5d075a12340c.png">

**Comment by guyvanbael** [comment]
@wilr 
fixed it on slack with Andrew...
Edit GoogleSitemapController.php like this
`    public function styleSheetIndex()
    {
        $html = $this->renderWith('xml-sitemapindex');
        $this->getResponse()->addHeader('Content-Type', 'text/xsl; charset="utf-8"');
        return $html;
    }

    public function styleSheet()
    {
        $html = $this->renderWith('xml-sitemap');
        $this->getResponse()->addHeader('Content-Type', 'text/xsl; charset="utf-8"');
        return $html;
    }`

and as for the stylesheetpath use
`<link rel="stylesheet" href="$resourceURL('wilr/silverstripe-googlesitemaps:css/style.css')" />`

**Comment by wilr** [comment]
Interesting, didn't have any issues on our PHP7 servers around the content type but better to be explicit! so I've added header and tagged a `2.1.2`

**Comment by guyvanbael** [comment]
2.1.2 is now fully SS4.1 compatible. Thanks for your coöperation @wilr
