### ISSUE TITLE
sitemap generating performance problems

### ISSUE THREAD

**Issue by RoyalPulp** [wilr/silverstripe-googlesitemaps#149]
Hi there,

generating a sitemap takes a huge amount of time on large websites.
Is there a working solution or ideas for caching ?

(SilverStripe 3.7.x)

Thanks for any helping ideas!

**Comment by wilr** [comment]
Hi,

See the queuedjobs module for an async version of a sitemap file. https://github.com/symbiote/silverstripe-queuedjobs/blob/master/src/Jobs/GenerateGoogleSitemapJob.php

Cheers

**Comment by RoyalPulp** [comment]
Thank you! I will give it a try soon... Do you know if it works with silverstripe-fluent  (also SilverStripe 3.x)

**Comment by wilr** [comment]
See https://github.com/wilr/silverstripe-googlesitemaps/issues/147
