### ISSUE TITLE
Google Sitemap error on google console

### ISSUE THREAD

**Issue by andykarwal** [wilr/silverstripe-googlesitemaps#150]
Google throws this error on all the sitemap pages:

![image](https://user-images.githubusercontent.com/6358071/45985627-3bd48180-c0bb-11e8-9d89-df413395f942.png)

**Comment by andykarwal** [comment]
I fixed this by adding  xmlns:xhtml="http://www.w3.org/1999/xhtml" to url set on Wirl/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss

**Comment by guyvanbael** [comment]
This is still an issue. I updated my module to dev-master version, but no luck
https://wings.be/sitemap.xml/sitemap/SilverStripe-CMS-Model-SiteTree/1

**Comment by TheBnl** [comment]
Could this be tagged as a release? 👍

**Comment by wilr** [comment]
@TheBnl Done `2.1.3`
