### ISSUE TITLE
alterCanIncludeInGoogleSitemap - How to use?

### ISSUE THREAD

**Issue by jo1hmk** [wilr/silverstripe-googlesitemaps#152]
I am trying to make use of alterCanIncludeInGoogleSitemap() in canView() on my DataObject. 
I'm kinda lost how to use it, this is what I have now 

```

    public function alterCanIncludeInGoogleSitemap($can = null)
    {

        if ($this->IsVisibleOnOverviewPage == false) {
            return false;
        }

        return true;
    }

```

But if I look in GoogleSitemapExtension.php the result of this part 

```

        // Allow override. In this case, since this can return multiple results, we'll use an "and" based policy.
        // That is if any value is false then the current value will be false. Only only if all are true will we
        // then return true.
        $override = $this->owner->invokeWithExtensions('alterCanIncludeInGoogleSitemap', $can);

        if ($override) {
            $can = min($override, $can);
        }

        return $can;
    }
```

is an array with false in it... Which somehow is interpreted as true (being an array, not false as value).

So... how to use it properly? Thanks in advance! :D

**Comment by wilr** [comment]
See https://github.com/wilr/silverstripe-googlesitemaps/pull/153

**Comment by jo1hmk** [comment]
Thanks @wilr! It worked!

**Comment by xyphoid** [comment]
Hi - would it be possible to get a release with this included at some point please? Running into the same issue

thanks,

**Comment by wilr** [comment]
@xyphoid 2.1.3 already is tagged with this

**Comment by wilr** [comment]
Ah sorry, no it wasn't tagged in 2.1.3 as I had a test failure. That's been fixed and pushed. I'm just waiting for CI then will tag `2.1.4`
