### ISSUE TITLE
Bug: empty sitemap on SS 4.4.1

### ISSUE THREAD

**Issue by extravio** [wilr/silverstripe-googlesitemaps#160]
I've tried the module on 2 newly updated SS 4.4.1 sites and the output only shows 1 entry
http://www.mysite.com/sitemap.xml/sitemap/SilverStripe-CMS-Model-SiteTree/1

![sitemap-output](https://user-images.githubusercontent.com/1171158/62265411-2a48cc80-b478-11e9-8833-964ca354e553.PNG)

Is there a problem on this version or am I missing something?
Thanks!

**Comment by wilr** [comment]
That's the sitemap index file. Click that link to see the pages.
