### ISSUE TITLE
SS4.4.3 : XML Parsing Error: XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by EEKimS** [wilr/silverstripe-googlesitemaps#161]
I may be missing something in configuration somewhere, but i am getting this error every time i try to load the sitemaps.

```
XML Parsing Error: XML or text declaration not at start of entity
Location: http://mysite/sitemap.xml?flush=1
Line Number 2, Column 1:
<?xml version="1.0" encoding="UTF-8"?>
^
```

the set up steps i did (might be missing something)

1. I ran the composer command to install
2. created the googlesitemaps.yml file in the _config folder
3. ran a dev/build?flush=all
4. tried to access sitemap.xml?flush=1, ?fush=all, and normally (where it just hangs)

Apologies if this is not enough info, i would be happy to help as i would like to actually be able to use this module.

Please Help :(

EDIT: I should include that currently this is on a Windows 10 / XAMPP setup -- but will be going live onto a linux server

**Comment by wilr** [comment]
@EEKimS Can you see if there is whitespace prior to the <?xml tag - this may be output if one of your PHP file has trialing whitespace after the ?> tag or before a <?

**Comment by EEKimS** [comment]
i looked in your templates and didn't see any whitespaces, if that's what you mean

**Comment by EEKimS** [comment]
@wilr  honestly i don't have any idea what would be generating whitespace anywhere

**Comment by wilr** [comment]
@EEKimS You may find some scripts online to help with the search to find the whitespace injecting file - i.e https://gist.github.com/AlexChittock/3742356

**Comment by EEKimS** [comment]
@wilr I was hoping to at least be able to do a workaround, but i can't seem to get the module to accept an extension either:

googlesitemaps.yml
```
---
Name: customgooglesitemaps
After: googlesitemaps
---
Wilr\GoogleSitemaps\GoogleSitemap:
  enabled: true
  objects_per_sitemap: 1000
  google_notification_enabled: false
  use_show_in_search: true

# attempting to fix whitespace issues for google sitemaps
Wilr\GoogleSitemaps\Control\GoogleSitemapController:
  extensions:
    - GoogleSitemapControllerExtension
```

GoogleSitemapControllerExtension.php
```
<?php

use SilverStripe\Core\Extension;
use SilverStripe\Control\Controller;
use Wilr\GoogleSitemaps\Control\GoogleSitemapController;

class GoogleSitemapControllerExtension extends Extension {

	public function index($url){
		var_dump("test overload method");
		return;
	}

}
```

Silverstripe 4 is a little hard to wrap my head around, but from everything i have done in the past i would have thought this would work.

Apologies if these are dumb questions, i am pulling my hair out at this point.

**Comment by EEKimS** [comment]
I managed to get the white space removed through an injector extension, but now the page just hangs -- think it has something to do with the stylesheets but there are no errors

**Comment by EEKimS** [comment]
that issue looks to be firefox not accepting the stylesheet headers or something. renders in chrome. I will close this, not sure if it's something in your list to fix
