### ISSUE TITLE
Google Search Console can not read sitemap.xml

### ISSUE THREAD

**Issue by tiefseh** [wilr/silverstripe-googlesitemaps#162]
Hi,
I installed the module. I can see the sitemap calling domain.com/sitemap.xml but
GSC says that it can not read it...

**Comment by spekulatius** [comment]
Have you ran dev/build on your server? Did you check if you can open the sitemap in the browser?

**Comment by lerni** [comment]
leading spaces (before `<php?`) can mess up xml - may check the source and make sure it's valid xml?
