### ISSUE TITLE
First line empty, leads to xml Error

### ISSUE THREAD

**Issue by Gregor-Agnes** [wilr/silverstripe-googlesitemaps#163]
Hi there and big thx for this great extension.
The standard sitemap
`/sitemap.xml/sitemap/SilverStripe-CMS-Model-SiteTree/1`

 has the first line empty
```

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='http://www.freiwillig-freiwillig.z3/sitemap.xml/styleSheet'?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
	
        <url>
```
which leads to an xml-error 
```
This page contains the following errors:
error on line 2 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.
```
and than empty page. Anyone experiences the same? What could I do to fix it?

I have several DataObject sitemaps ,too. They all work like a charm. :)

**Comment by wilr** [comment]
@Gregor-Agnes I believe this would be caused by your application code. It contains a leading or trailing whitespace after your `<?php or ?>` tags.

**Comment by wilr** [comment]
Have checked on a default clean install and no whitespace line appears on that.

**Comment by Gregor-Agnes** [comment]
> @Gregor-Agnes I believe this would be caused by your application code. It contains a leading or trailing whitespace after your `<?php or ?>` tags.

That's it, big thx! I've taken over the page and my predecessors have had one newline in one controller of the app just before <?php

Have a nice WE!
