### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by GuySartorelli** [wilr/silverstripe-googlesitemaps#171]
The changelog hasn't been updated since 0.2
I know it will be a pain to retroactively update, but it would be good to have a list of what was fixed in previous versions (both to track possible regressions and as a way to see if an issue someone has in a specific version has been resolve in a more recent version).

**Comment by wilr** [comment]
Happy to update it and keep it updated in future if people find it useful but I find the Github compare UI is way more useful (https://github.com/wilr/silverstripe-googlesitemaps/compare/2.1.6...2.1.7)
