### ISSUE TITLE
only has_one and has_many images are included not many_many

### ISSUE THREAD

**Issue by sunnysideup** [wilr/silverstripe-googlesitemaps#172]
see: https://github.com/wilr/silverstripe-googlesitemaps/blob/master/src/Extensions/GoogleSitemapSiteTreeExtension.php#L137-L161

Also, Framework should have a function that allows you to loop through all relationships on one go, without having to do the hasOne, HasMany, ManyMany, BelongManyMany. I realise that this is for framework and not for this module, but still interesting to look at if perhaps this exists already or can be dealt with some other way.

**Comment by obj63mc** [comment]
So as a note this fix now is breaking site maps that have a many many relationship to the same class.

An example is the following on the SilverStripe BlogPost class - 

     private static $many_many = [
        'RelatedArticles' => BlogPost::class
    ];
    private static $belongs_many_many = [
        'BlogPosts' => BlogPost::class.'RelatedArticles'
    ];

This is now throwing an exception - Emergency] Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class SilverStripe\Blog\Model\BlogPostRelatedArticles does not exist in ...

**Comment by obj63mc** [comment]
This fix, on line 171 is causing an issue when trying to look at many many relationships that are linked to the same class.

An example of this is say you have a BlogPost that has related posts (which are of the same type)

    private static $many_many = [
        'RelatedArticles' => BlogPost::class
    ];

    private static $belongs_many_many = [
        'BlogPosts' => BlogPost::class.'.RelatedArticles'
    ];

The sitemap generation looking for images is now throwing the following error - 

`[Emergency] Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class SilverStripe\Blog\Model\BlogPost.RelatedArticles does not exist`

> Trace
SilverStripe\Core\Injector\InjectionCreator->create(SilverStripe\Blog\Model\BlogPost.RelatedArticles, Array)
Injector.php:594
SilverStripe\Core\Injector\Injector->instantiate(Array, SilverStripe\Blog\Model\BlogPost.RelatedArticles, singleton)
Injector.php:1002
SilverStripe\Core\Injector\Injector->getNamedService(SilverStripe\Blog\Model\BlogPost.RelatedArticles, 1, Array)
Injector.php:955
SilverStripe\Core\Injector\Injector->get(SilverStripe\Blog\Model\BlogPost.RelatedArticles)
functions.php:34
singleton(SilverStripe\Blog\Model\BlogPost.RelatedArticles)
GoogleSitemapSiteTreeExtension.php:171
Wilr\GoogleSitemaps\Extensions\GoogleSitemapSiteTreeExtension->ImagesForSitemap()

**Comment by wilr** [comment]
@obj63mc Try this fix - https://github.com/wilr/silverstripe-googlesitemaps/pull/174
