### ISSUE TITLE
SilverStripe 4.x Googlesitemap -  sitemap.xml Image did not exist

### ISSUE THREAD

**Issue by marccomia** [wilr/silverstripe-googlesitemaps#178]
Hi Guys,

I am using this silverstripe-googlesitemaps latest version, at first it works fine but now i am getting an error even though i did the dev/build and the flush. Its so weird now google failed to index my website. 

please see error below.  Thank you for your help.

E.g
https://www.yourdomain.com/sitemap.xml/sitemap/SilverStripe-CMS-Model-SiteTree/1
Errors hows:
[Emergency] Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class SilverStripe\Lessons\Image does not exist in public_html/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:17 

Trace::
SilverStripe\Core\Injector\InjectionCreator->create(SilverStripe\Lessons\Image, Array)
Injector.php:594
SilverStripe\Core\Injector\Injector->instantiate(Array, SilverStripe\Lessons\Image, singleton)
Injector.php:1002
SilverStripe\Core\Injector\Injector->getNamedService(SilverStripe\Lessons\Image, 1, Array)
Injector.php:955
SilverStripe\Core\Injector\Injector->get(SilverStripe\Lessons\Image)
functions.php:34
singleton(SilverStripe\Lessons\Image)
GoogleSitemapSiteTreeExtension.php:138
Wilr\GoogleSitemaps\Extensions\GoogleSitemapSiteTreeExtension->ImagesForSitemap()
call_user_func_array(Array, Array)
Extensible.php:144
SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(SilverStripe\Lessons\ContactPage, Array)
CustomMethods.php:61
SilverStripe\View\ViewableData->__call(ImagesForSitemap, Array)
call_user_func_array(Array, Array)
ViewableData.php:485
SilverStripe\View\ViewableData->obj(ImagesForSitemap, , 1)
ViewableData.php:532
SilverStripe\View\ViewableData->hasValue(ImagesForSitemap, , 1)
DataObject.php:4074
SilverStripe\ORM\DataObject->hasValue(ImagesForSitemap, , 1)
SSViewer_Scope.php:323
SilverStripe\View\SSViewer_Scope->__call(hasValue, Array)
SSViewer_DataPresenter.php:309
SilverStripe\View\SSViewer_DataPresenter->__call(hasValue, Array)
.cachevendor.wilr.silverstripe-googlesitemaps.templates.Wilr.GoogleSitemaps.Control.GoogleSitemapController_sitemap.ss:52
include(/tmp/silverstripe-cache-php7.1.33-home-csgastro-public_html/csgastro/.cachevendor.wilr.silverstripe-googlesitemaps.templates.Wilr.GoogleSitemaps.Control.GoogleSitemapController_sitemap.ss)
SSViewer.php:602
SilverStripe\View\SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.1.33-home-csgastro-public_html/csgastro/.cachevendor.wilr.silverstripe-googlesitemaps.templates.Wilr.GoogleSitemaps.Control.GoogleSitemapController_sitemap.ss, SilverStripe\View\ViewableData_Customised, , Array, )
SSViewer.php:674
SilverStripe\View\SSViewer->process(SilverStripe\View\ViewableData_Customised)
Controller.php:288
SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, sitemap)
RequestHandler.php:202
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
Controller.php:212
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
Director.php:360
SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
VersionedHTTPMiddleware.php:41
SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ExecMetricMiddleware.php:20
SilverStripe\Control\Middleware\ExecMetricMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ConfirmationMiddleware.php:254
SilverStripe\Control\Middleware\ConfirmationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ConfirmationMiddleware.php:254
SilverStripe\Control\Middleware\ConfirmationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
BasicAuthMiddleware.php:68
SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AuthenticationMiddleware.php:61
SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
CanonicalURLMiddleware.php:190
SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPCacheControlMiddleware.php:42
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ChangeDetectionMiddleware.php:28
SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
FlushMiddleware.php:27
SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
RequestProcessor.php:66
SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
SessionMiddleware.php:20
SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AllowedHostsMiddleware.php:60
SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrustedProxyMiddleware.php:176
SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65
SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
Director.php:369
SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
HTTPApplication.php:117
SilverStripe\Control\HTTPApplication::SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
call_user_func(Closure, SilverStripe\Control\HTTPRequest)
HTTPApplication.php:136
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
HTTPApplication.php:137
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
HTTPApplication.php:118
SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
index.php:23

**Comment by wilr** [comment]
I'm picking its not an issue with the module but your `ContactPage` class is missing a `use SilverStripe\Assets\Image;` statement.

**Comment by marccomia** [comment]
Thank you so much. Its fixed now.
