### ISSUE TITLE
Pinging updates to Bing no longer works

### ISSUE THREAD

**Issue by scott1702** [wilr/silverstripe-googlesitemaps#185]
Bing has deprecated the use of the [ping URL](https://github.com/wilr/silverstripe-googlesitemaps/blob/main/src/GoogleSitemap.php#L94) for updates—https://www.ctrl.blog/entry/sitemap-ping-indexnow.html. 
They have since adopted a different approach using indexNow with API keys that is required for Bing to get live updates to sitemap changes https://www.bing.com/indexnow.

**Comment by samandeggs** [comment]
Hi,

This is now deprecated, as per https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping - and it seemingly rolled over on the new year to be fully removed. This will effect both the v5 and v4 versions of SilverStripe, and a `2` and `3` version should preferably have an pr/update to remove the ping functionality to avoid errors/warnings here.

```
E_WARNING: file_get_contents(http://www.google.com/webmasters/sitemaps/ping?sitemap=https%3A%2F%2F<yourwebsite>.com%2Fsitemap.xml): failed to open stream: HTTP request failed! HTTP/1.0 404 Sitemaps ping is deprecated. See https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping.
```

**Comment by jareddreyerss** [comment]
Removed in https://github.com/wilr/silverstripe-googlesitemaps/pull/197
sorry @wilr forgot to tag this on the PR.
