### ISSUE TITLE
Issue with Subsites module

### ISSUE THREAD

**Issue by tazzydemon** [wilr/silverstripe-googlesitemaps#25]
The subsites module may have a different result for

$page->AbsoluteLink()

than is actually being used in the browser - especially during the test phase when one might have a test url as well as the real one configured

Thus the line 154 in GoogleSitemap.php fails: 

if(($pageHttp == $hostHttp) && !($page instanceof ErrorPage)) {

I cant see any good reason why this comparison is made and it breaks subsites under test therefore I changed it to

if(!($page instanceof ErrorPage)) {

After this its a question of sorting the domain order, or primary domain settings to get what you want  when you are using a different test url.

**Comment by wilr** [comment]
Looks to be resolved in the latest build
