### ISSUE TITLE
$Priority is not correctely formated as a floa

### ISSUE THREAD

**Issue by dacar** [wilr/silverstripe-googlesitemaps#26]
Hi, i am just testing the googlesitemaps module for SS 3.2. There is a problem to get a valid .xml because of the $Priority. in my sitemap.xml $Priority is not correctely formated as a float: <priority>0,9</priority>. Becuase of this i get an NaN% instead of a value.

I am using the translatable module. In my _config.php i have set: setlocale (LC_ALL, 'de_DE@euro', 'de_DE.UTF-8', 'de_DE', 'de', 'ge');

Is there a way to set setlocale(LC_NUMERIC, 'en_US') just for the sitemap.xml?

**Comment by wilr** [comment]
Fixed in 9b7c14ab
