### ISSUE TITLE
Support adding objects via YML

### ISSUE THREAD

**Issue by Firesphere** [wilr/silverstripe-googlesitemaps#92]
Title speaks for itself.

**Comment by smokeycam** [comment]
Big +1 on this one

**Comment by wilr** [comment]
@Firesphere @smokeycam any reason you're unhappy about the PHP API? it would be easy to add. Simply have

GoogleSitemap:
  register_dataobjects:
    - Foo
    - Bar

**Comment by smokeycam** [comment]
Hiya @wilr , maybe its me, that I am not doing this correctly. I have this in my modules YML files, but not having any effect.. any ideas?

GoogleSitemap:
  register_dataobjects:
    - Property
    - 'Daily'

**Comment by wilr** [comment]
So that won't work, was just wondering if that sort of YAML API is what you wanted.

**Comment by tractorcow** [comment]
I think the idea is that could be the API. Someone would still need to add support for it in the module. :D

**Comment by smokeycam** [comment]
Oh yes, that would be ideal for me. I can always just use the _config.php
in the interim. As i am relatively new to Silverstipe and was just setting
up a 'standardised(?)' configuration setup. Having said that, a little off
topic, but is the YML config setup with Silverstipe the preferred way, or
is it an 'either one or both' (yml/_config.php) senario?

Thanks for clearing that all up.

Cheers!
